# Gems
gems: [jekyll-paginate]

# Setup
title:               'scalar vector tensor'
# tagline:             'machine-made' # this should be a random message
description:         'Projects and other things by <a href="https://twitter.com/achimkoh" target="_blank">@achimkoh</a>.'
url:                 https://scalarvectortensor.net # the base hostname & protocol for your site
paginate:            3
paginate_path:       "page:num"
permalink:           /:title
timezone:            America/New_York


# About/contact
author:
  name:              Achim Koh
  url:               https://twitter.com/achimkoh
  email:             achim.koh@gmail.com