# SITE CONFIGURATION
baseurl: ""
url: "https://scalarvectortensor.net"
title: Koh Achim # site's title
description: "machine learning, digital culture, and the infrastructure of knowledge production" # used by search engines

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Koh Achim # blog's title
  avatar: 
  favicon: assets/favicon.ico
  favicon_png: assets/favicon.png
  favicon_apple: assets/apple-touch-icon.png
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
    Achim is a <a class='trigger research'>researcher</a>, <a class='trigger development'>programmer</a> and <a class='trigger translation'>translator</a>.<br>His work engages the technopolitics of machine learning, digital art, musical interfaces, and the web.
  # header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   achim dot koh at gmail dot com

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  github: "achimkoh"
  instagram:
  keybase:
  linkedin:  # Full URL
  soundcloud:
  steam:
  tumblr:
  twitter: "achimkoh" # "twitter username"
  vimeo:
  wordpress:
  youtube:
  arena: "achim-koh"

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: # true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: # true
    tags:
      icon: "tags"
      enabled: # true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  # google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
# paginate: 5
# paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  projects:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-admin]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js"]
